name: Deploy Tremtec

on:
  push:
    branches:
      - main
    paths:
      - "apps/tremtec/**"
      - "apps/tremtec_shared/**"
      - "config/**"
      - "Dockerfile"
      - "mix.exs"
      - "mix.lock"

jobs:
  deploy:
    name: Deploy tremtec app
    runs-on: ubuntu-latest
    environment: production
    concurrency: deploy-tremtec # ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --config apps/tremtec/fly.toml --depot=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
